# Chroma 向量存储配置
collection_name: agent
persist_directory: chroma_db
k: 3
data_path: data
md5_hex_store: md5.txt
allow_knowledge_file_type: ["txt", "pdf"]

# 文本分割配置
chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", "，"]
